[tool.poetry]
name = "rwbasic"
version = "0.1.0"
description = "Experiment in a BASIC-like language"
authors = ["Rich Wareham <rich@richwareham.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "rwbasic"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
